baseURL = "https://oczadly.io"
theme = "LoveIt"
defaultContentLanguage = "en"
languageCode = "en"
languageName = "English"
title = "oczadly.io - production-ready tooling. Clean solutions."

[languages]
  [languages.en]
    weight = 1
    languageCode = "en"
    languageName = "English"
    [[languages.en.menu.main]]
      weight = 1
      identifier = "posts"
      name = "Posts"
      url = "/posts/"
    [[languages.en.menu.main]]
      weight = 2
      identifier = "about"
      name = "About"
      url = "/about/"

  [languages.pl]
    weight = 2
    languageCode = "pl"
    languageName = "Polski"
    [[languages.pl.menu.main]]
      weight = 1
      identifier = "posts"
      name = "Wpisy"
      url = "/posts/"
    [[languages.pl.menu.main]]
      weight = 2
      identifier = "about"
      name = "O blogu"
      url = "/about/"

[markup]
  [markup.highlight]
    noClasses = false

[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    pre = ""
    post = ""
    name = "Posts"
    url = "/posts/"
    title = ""

[params]
  description = "Patterns for platform engineering and AI workflows."
  title = "oczadly.io - production-ready tooling. Clean solutions."

  [params.author]
    name = "Paweł Oczadły"
    email = "p@oczadly.io"

  [params.footer]
    hugo = false
    since = 2025

  [params.header]
    [params.header.title]
      pre = "<text class=\"logo\"><span class=\"oczadly\">oczadly</span><span class=\"dot-io\">.io</span></text>"
      # Override the default name parameter
      name = ""

  [params.home]
    [params.home.profile]
      enable = true
      avatarURL = "/images/logo-avatar.png"
      title = "<text class=\"logo\"><span class=\"oczadly\">oczadly</span><span class=\"dot-io\">.io</span></text>"
      subtitle = "Reusable, production-ready solutions for cloud architecture, platform engineering and AI-native tooling."
  
  [params.page]
    [params.page.share]
      X = true
      Facebook = true
      Linkedin = true
      # Disable the ones which are enabled by default
      HackerNews = false
      Line = false
      Weibo = false
      Diaspora = false
      Telegram = false

  [params.social]
    Email = "p@oczadly.io"
    GitHub = "paweloczadly"
    Linkedin = "paweloczadly"
    Strava = "67135909"
